### ISSUE TITLE
Winston's data

### ISSUE THREAD

**Issue by WinstonWantsAUserName** [open-spaced-repetition/fsrs-vs-sm17#14]
[SM16-v-SM17.csv](https://github.com/open-spaced-repetition/fsrs-vs-sm17/files/12505420/SM16-v-SM17.csv)

**Comment by L-M-Sherlock** [comment]
@all-contributors please add @WinstonWantsAUserName for data.

**Comment by L-M-Sherlock** [comment]
感谢你的分享～
