### ISSUE TITLE
NoHeartPen's [Data]

### ISSUE THREAD

**Issue by NoHeartPen** [open-spaced-repetition/fsrs-vs-sm17#20]
**Data file**

You can find `SM16-v-SM17.csv` in `sm18/systems/{collection_name}/stats` folder. The private content is stored in column `Title`. I recommend removing it before uploading to GitHub and sharing. Don't forget to make a copy before you delete it. Then you can drag and drop the file here.

你可以在 `sm18/systems/{collection_name}/stats` 文件夹中找到 `SM16-v-SM17.csv` 文件。`Title` 列中可能包含隐私信息，建议在上传到 GitHub 分享之前删除它。删之前别忘了备份。然后你就可以将文件拖进这里上传分享。

[SM16-v-SM17.csv](https://github.com/open-spaced-repetition/fsrs-vs-sm17/files/12513052/SM16-v-SM17.csv)

说明一下：虽然文件里包含了最近一年的数据，但我用 SuperMemo 用得不是那么多，大部分都是「三」天打鱼「三十」天晒网的状态233，希望我的「脏」数据也能有一定的参考价值:)

**Comment by L-M-Sherlock** [comment]
@all-contributors please add @NoHeartPen for data.
