### ISSUE TITLE
Add FSRS v4 and FSRS v3 to the comparison

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-vs-sm17#47]
Currently the table just says "FSRS".
![image](https://github.com/open-spaced-repetition/fsrs-vs-sm17/assets/83031600/1bde5479-4717-47dc-a2dc-c871cf4d02fb)
Ideally, both FSRS v3 and FSRS v4 should be added. If you don't want to change v3 code just for benchmarking that's fine, although I think it would be interesting to see the difference. Also, please specify which version of FSRS is used in the benchmark. I know it's v4, but I still think it would be better to specify that explicitly.

**Comment by L-M-Sherlock** [comment]
I want to remove Universal Metric if we have to add FSRS v3 to the comparison.

**Comment by Expertium** [comment]
Why remove it?

**Comment by L-M-Sherlock** [comment]
> Why remove it?

UM for 3 algorithms needs 3 cross comparisons. UM for 4 algorithms needs 6 cross comparisons.

**Comment by L-M-Sherlock** [comment]
You can review this PR: #48

**Comment by Expertium** [comment]
I thought that UM requires only 2 algorithms.

**Comment by L-M-Sherlock** [comment]
> I thought that UM requires only 2 algorithms.

To calculate the UM of FSRSv4, we need to use FSRSv3, SM-17 and SM-16 as the classifiers.

**Comment by Expertium** [comment]
Now that I think about, maybe it's a good thing that UM is gone, since it wasn't used in the other benchmark repo, which is inconsistent. Now the metrics used in all repos are the same.
