### ISSUE TITLE
Gather more data

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-vs-sm17#49]
I know that this isn't very helpful, and I can't contribute anything substantial or help in any way, so I'm just opening this issue to remind you that right now this benchmark is based on very limited data, and ideally we need 1000000+ reviews. So if you have any ideas where to find more SuperMemo users who are willing to share their data, it would be great.

**Comment by Expertium** [comment]
@L-M-Sherlock also, please benchmark FSRS v4.5.

**Comment by Expertium** [comment]
I did a little bit of analysis. Confidence intervals are proportional to sqrt(n), where n is the number of users. I analyzed the confidence intervals under the assumption that the means stay the same, and according to my math, we would need 54 SM collections to show that FSRS-4.5 is more accurate than SM-17, specifically, to show that the confidence intervals do not overlap. But just to be safe, at least 65 is necessary. This isn't so bad, I would recommend you to ask on r/SuperMemo and r/Super_Memo, as well as [in SuperMemo discord](https://supermemopedia.com/wiki/Invitation_to_Discord_Channels).

**Comment by L-M-Sherlock** [comment]
I'm afraid that I'm not welcome to the SuperMemo community now. I prefer to wait for the SuperMemo API, and then I can run the API in fsrs-benchmark directly if it's not very expensive.

**Comment by Expertium** [comment]
Ok. Btw, what will you do with this repo once the API becomes available?

**Comment by L-M-Sherlock** [comment]
> what will you do with this repo once the API becomes available?

I plan to archive this repo when the API becomes available.
