### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by Shore3145** [open-spaced-repetition/fsrs-vs-sm17#5]
**Data file**

You can find `SM16-v-SM17.csv` in `sm18/systems/{collection_name}/stats` folder. The private content is stored in column `Title`. I recommend removing it before uploading to GitHub and sharing. Don't forget to make a copy before you delete it. Then you can drag and drop the file here.
[SM16-v-SM17.csv](https://github.com/open-spaced-repetition/fsrs-vs-sm17/files/12498833/SM16-v-SM17.csv)
[原神.csv](https://github.com/open-spaced-repetition/fsrs-vs-sm17/files/12498834/default.csv)
[上古合集.csv](https://github.com/open-spaced-repetition/fsrs-vs-sm17/files/12498835/default.csv)

你可以在 `sm18/systems/{collection_name}/stats` 文件夹中找到 `SM16-v-SM17.csv` 文件。`Title` 列中可能包含隐私信息，建议在上传到 GitHub 分享之前删除它。删之前别忘了备份。然后你就可以将文件拖进这里上传分享。

**Comment by L-M-Sherlock** [comment]
@all-contributors please add @Shore3145 for data.

**Comment by L-M-Sherlock** [comment]
感谢你的贡献！
