### ISSUE TITLE
[Feature Request] Add FSRS v4 too, not just FSRS-4.5

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-vs-sm17#52]
The title says it all.

**Comment by L-M-Sherlock** [comment]
I couldn't run the FSRSv4 and FSRS-4.5 in the same script.

**Comment by Expertium** [comment]
But the main benchmark repo has both. We should keep things consistent.

**Comment by L-M-Sherlock** [comment]
If we update the dataset, I will have to remove FSRSv4 in the benchmark.

**Comment by Expertium** [comment]
I don't understand. Why would you have to remove FSRS v4 when updating the dataset?

**Comment by Expertium** [comment]
Unrelated to the current issue, but I think you should add a link to the main benchmark repo to README.

**Comment by L-M-Sherlock** [comment]
Because the model in the script is imported from fsrs-optimizer package. It's impossible to keep two different versions of the same package in the same environment.

**Comment by Expertium** [comment]
Ah, I see. How about making two separate fsrs-optimizer repos, for v4 and for 4.5?

**Comment by L-M-Sherlock** [comment]
OK. I will do it in Feb.
