### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by reallyyy** [open-spaced-repetition/fsrs-vs-sm17#8]
**Data file**

You can find `SM16-v-SM17.csv` in `sm18/systems/{collection_name}/stats` folder. The private content is stored in column `Title`. I recommend removing it before uploading to GitHub and sharing. Don't forget to make a copy before you delete it. Then you can drag and drop the file here.
[SM16-v-SM17.csv](https://github.com/open-spaced-repetition/fsrs-vs-sm17/files/12504274/SM16-v-SM17.csv)

你可以在 `sm18/systems/{collection_name}/stats` 文件夹中找到 `SM16-v-SM17.csv` 文件。`Title` 列中可能包含隐私信息，建议在上传到 GitHub 分享之前删除它。删之前别忘了备份。然后你就可以将文件拖进这里上传分享。

**Comment by L-M-Sherlock** [comment]
<img width="771" alt="image" src="https://github.com/open-spaced-repetition/fsrs-vs-sm17/assets/32575846/4fa7771d-8564-4efd-a40d-304ffd1025f9">

You data seems weird. The `R` should be in 0~1.

**Comment by L-M-Sherlock** [comment]
I will concat `0.` to `R`.

**Comment by L-M-Sherlock** [comment]
@all-contributors please add @reallyyy for data.

**Comment by L-M-Sherlock** [comment]
Thanks for your contribution!
